### PR TITLE
feat: Makes layout more responsive and adds mobile menu.

### PR DESCRIPTION
**Pull request by tomwalsh-home**

### CODE REVIEW

**Comment by tomwalsh-home** [comment]
@yakuter, added the download links to the mobile menu - someone will need to add the URLs, but i've added that as a prop now, so it should be nice and easy 👍

**Comment by yakuter** [comment]
Hi @tomwalsh-home thanks for great PR. We were working on the project at the same time. So there are 2 conflicts. Can you solve and push them again. I would be happy to merge.

**Comment by tomwalsh-home** [comment]
hi @yakuter , should be fixed now :)

**Comment by yakuter** [comment]
> hi @yakuter , should be fixed now :)

Seems great. Thank you so much @tomwalsh-home

**Pull request merged**
